packages:
  - "packages/*"

minimumReleaseAge: 60
trustPolicy: no-downgrade
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - deslop-js
  - "@voidzero-dev/*"
  - vite-plus
  - "@vitest/*"
  - vite
  - vitest
  - "@oxc-project/*"
  - "@oxlint/*"
  - oxlint
  - oxfmt
  - oxlint-tsgolint

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@sentry/cli"
  - esbuild
  - unrs-resolver

overrides:
  vite: "https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856"
  vitest: "4.1.9"
  oxlint: ">=1.66.0 <1.67.0"
  oxlint-tsgolint: "^0.23.0"
