minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - "@oxc-project/*"
  - "@oxlint/*"
  - "@oxfmt/*"
  - "@oxlint-tsgolint/*"
  - "@rolldown/*"
  - "@tsdown/*"
  - oxlint
  - oxfmt
  - oxlint-tsgolint
  - tsdown
  - rolldown
  - vitest
  - "@vitest/*"
packages:
  - "packages/*"

blockExoticSubdeps: true

overrides:
  vite: "catalog:"
  vitest: "catalog:"
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@sentry/cli"
  - esbuild
  - unrs-resolver
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.1d7ba811f0e456640b0e761e8e8acf77d1ad3251
  vitest: 4.1.9
  vite-plus: 0.0.0-commit.1d7ba811f0e456640b0e761e8e8acf77d1ad3251
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
